import os
import warnings
from fastapi import FastAPI, UploadFile, File, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from azure.core.credentials import AzureKeyCredential
from dotenv import load_dotenv
import uvicorn
import tempfile
from pydantic import BaseModel
import base64
from openai import AzureOpenAI
from fastapi.templating import Jinja2Templates


# Load environment variables from .env file
load_dotenv(override=True)

# Define base directories
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")

app = FastAPI(title="Image 2 Text")

# Set up templates and static files directories
templates = Jinja2Templates(directory=TEMPLATES_DIR)
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

# Add CORS middleware to allow cross-origin requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Modify this in production to only allow specific origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Azure OpenAI client
client = AzureOpenAI(
    api_version=os.environ.get("AZURE_OPENAI_API_VERSION", "2024-12-01-preview"),
    azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT"),
    api_key=os.environ.get("AZURE_OPENAI_API_KEY")
)



class ImageAnalysisResponse(BaseModel):
    description: str



async def analyze_image_with_gpt4_vision(image_path, prompt="Describe this image in detail."):
    """
    Analyze an image using Azure OpenAI's GPT-4.1 vision capabilities
    
    Args:
        image_path: Path to the image file
        prompt: Instructions for the model about what to analyze in the image
        
    Returns:
        The text description generated by the model
    """
    # Get the deployment name from env vars
    deployment_name = os.environ.get("AZURE_OPENAI_DEPLOYMENT_NAME")
    
    # Read and encode the image as base64
    with open(image_path, "rb") as image_file:
        base64_image = base64.b64encode(image_file.read()).decode('utf-8')
    
    try:
        # Call Azure OpenAI with the image using the new SDK format
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a helpful assistant that can describe images accurately."},
                {
                    "role": "user", 
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{base64_image}"}}
                    ]
                }
            ],
            max_tokens=2000
        )
        
        # Extract and return the response text
        return response.choices[0].message.content
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error from Azure OpenAI: {str(e)}")



@app.get("/", response_class=HTMLResponse)
async def root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})



@app.post("/image-to-text", response_model=ImageAnalysisResponse)
async def image_to_text(file: UploadFile = File(...), prompt: str = "Describe this image in detail, focusing on any charts, graphs, or text visible."):
    """
    Endpoint to analyze an image using Azure OpenAI's GPT-4.1 vision capabilities
    
    Args:
        file: The uploaded image file
        prompt: Instructions for the model about what to analyze in the image
        
    Returns:
        A JSON response with the text description
    """
    # Check if the file is an image
    allowed_extensions = ['.jpg', '.jpeg', '.png', '.bmp']
    file_ext = os.path.splitext(file.filename.lower())[1] if file.filename else ''
    
    if not any(file_ext.endswith(ext) for ext in allowed_extensions):
        raise HTTPException(status_code=400, detail="Only image files (jpg, jpeg, png, bmp) are supported")

    try:
        # Save the uploaded file to a temporary location
        with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as temp_file:
            temp_file.write(await file.read())
            temp_file_path = temp_file.name

        try:
            # Process the image with GPT-4.1 Vision
            description = await analyze_image_with_gpt4_vision(temp_file_path, prompt)
            
            # Create a response
            response = ImageAnalysisResponse(description=description)
            return response
            
        finally:
            # Clean up the temporary file
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")



if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)